'use client';

import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Role, ROLE_NAMES, ROLE_ICONS } from '@/lib/constants';

interface LeaderRoleConfiguratorProps {
  gameState: any;
  emit: (event: string, payload: any) => Promise<any>;
  setError: (err: string) => void;
}

export default function LeaderRoleConfigurator({ gameState, emit, setError }: LeaderRoleConfiguratorProps) {
  const [roles, setRoles] = useState<Role[]>([]);
  const [loading, setLoading] = useState(true);
  const [openDropdown, setOpenDropdown] = useState<number | null>(null);

  // When mounted, roles are generated by backend and sent via 'setup:roles-generated'
  // But since we are showing this *after* receiving 'setup:roles-generated', 
  // we actually need to intercept it in `leader/page.tsx` and pass it down.
  // Wait, `leader/page.tsx` didn't catch `setup:roles-generated` yet.
  
  // Actually, I can just recalculate the default distribution here or listen to the event globally.
  // Let's implement the generation logic locally as default, and then send the final array to `setup:roles-confirmed`.
  useEffect(() => {
    // Generate default distribution
    const playerCount = gameState.players.filter((p: any) => p.isAlive !== false).length;
    const totalMafia = Math.ceil(playerCount / 4);
    const totalCitizens = playerCount - totalMafia;

    const mafiaOrder = [Role.GODFATHER, Role.SILENCER, Role.CHAMELEON, Role.MAFIA_REGULAR];
    const citizenOrder = [Role.SHERIFF, Role.DOCTOR, Role.SNIPER, Role.POLICEWOMAN, Role.NURSE, Role.CITIZEN];

    let generated: Role[] = [];
    
    for (let i = 0; i < totalMafia; i++) {
       generated.push(i < mafiaOrder.length - 1 ? mafiaOrder[i] : Role.MAFIA_REGULAR);
    }
    
    for (let i = 0; i < totalCitizens; i++) {
       generated.push(i < citizenOrder.length - 1 ? citizenOrder[i] : Role.CITIZEN);
    }

    setRoles(generated);
    setLoading(false);
  }, [gameState.players]);

  const handleRoleChange = (index: number, newRole: Role) => {
    const newRoles = [...roles];
    newRoles[index] = newRole;
    setRoles(newRoles);
  };

  const handleConfirm = async () => {
    try {
      setLoading(true);
      await emit('setup:roles-confirmed', { roomId: gameState.roomId, roles });
    } catch (err: any) {
      setError(err.message);
      setLoading(false);
    }
  };

  const allRolesList = Object.values(Role);

  if (loading) return <div className="text-center p-12 text-[#555] font-mono tracking-widest">INITIALIZING ROSTER...</div>;

  const mafiaRoles = roles.filter(r => [Role.GODFATHER, Role.SILENCER, Role.CHAMELEON, Role.MAFIA_REGULAR].includes(r));
  const citizenRoles = roles.filter(r => ![Role.GODFATHER, Role.SILENCER, Role.CHAMELEON, Role.MAFIA_REGULAR].includes(r));

  return (
    <div className="mb-10 w-full max-w-5xl mx-auto">
      {/* Header Container */}
      <div className="bg-black/30 border border-[#2a2a2a] rounded-xl p-8 mb-8 backdrop-blur-sm relative overflow-hidden text-center">
        <div className="absolute left-0 top-0 w-1 h-full bg-[#C5A059]/40" />
        <h2 className="text-3xl font-black text-white" style={{ fontFamily: 'Amiri, serif' }}>تدقيق وإعداد المهام السرية</h2>
        <p className="text-[#808080] font-mono tracking-[0.3em] mt-3 uppercase text-xs">ROLE COMPOSITION MATRIX CONFIGURATION</p>
      </div>

      <div className="flex flex-col gap-6 mb-8 w-full">
        {/* Mafia Column */}
        <div className="bg-black/40 border border-[#8A0303]/30 rounded-xl p-6 backdrop-blur-sm relative z-20">
          <div className="absolute top-0 right-0 w-full h-[1px] bg-gradient-to-l from-transparent via-[#8A0303]/50 to-transparent rounded-t-xl" />
          <div className="flex items-center justify-between mb-6 pb-4 border-b border-[#8A0303]/20">
            <h3 className="text-sm font-mono text-[#8A0303] uppercase tracking-[0.2em] font-bold">
              SYNDICATE (المافيا)
            </h3>
            <span className="bg-[#8A0303]/20 text-[#8A0303] font-mono border border-[#8A0303]/30 rounded px-3 py-1 text-xs">
              {mafiaRoles.length} OP(s)
            </span>
          </div>
          
          <div className="flex flex-wrap gap-3">
            {roles.map((r, i) => {
              const isMafia = [Role.GODFATHER, Role.SILENCER, Role.CHAMELEON, Role.MAFIA_REGULAR].includes(r);
              if (!isMafia) return null;
              return (
                <div key={i} className="bg-[#0a0a0a] border border-[#8A0303]/20 rounded-lg p-2 flex items-center gap-3 hover:border-[#8A0303]/60 transition-colors group flex-1 min-w-[200px] sm:flex-none">
                  <div className="w-12 h-12 shrink-0 rounded bg-[#111] border border-[#8A0303]/30 flex items-center justify-center text-2xl grayscale opacity-70 group-hover:opacity-100 transition-opacity">
                    {ROLE_ICONS[r]}
                  </div>
                  <div className="relative flex-1">
                    <div 
                      onClick={() => setOpenDropdown(openDropdown === i ? null : i)}
                      className="w-full bg-transparent text-white font-mono text-xs md:text-sm px-3 py-2 cursor-pointer tracking-widest font-bold flex justify-between items-center"
                      dir="ltr"
                    >
                      <span className="text-[#C5A059] pr-2 whitespace-nowrap">{ROLE_NAMES[r]}</span>
                      <span className="text-[#8A0303] text-[10px] shrink-0">▼</span>
                    </div>

                    <AnimatePresence>
                      {openDropdown === i && (
                        <motion.div 
                          initial={{ opacity: 0, y: -10 }} 
                          animate={{ opacity: 1, y: 0 }} 
                          exit={{ opacity: 0, y: -10 }}
                          className="absolute top-full right-0 w-[220px] mt-2 bg-[#0c0c0c] border border-[#8A0303]/40 rounded-lg shadow-2xl z-50 overflow-hidden"
                          dir="rtl"
                        >
                          <div className="max-h-[220px] overflow-y-auto">
                            {allRolesList.map(role => (
                              <div 
                                key={role}
                                onClick={() => { handleRoleChange(i, role); setOpenDropdown(null); }}
                                className={`px-4 py-3 flex items-center gap-3 cursor-pointer hover:bg-[#8A0303]/20 transition-colors ${r === role ? 'bg-[#8A0303]/10 border-l-2 border-[#8A0303]' : ''}`}
                              >
                                <span className="text-xl grayscale opacity-70 w-6 text-center">{ROLE_ICONS[role]}</span>
                                <span className="font-mono text-xs text-[#C5A059] flex-1">{ROLE_NAMES[role]}</span>
                              </div>
                            ))}
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Citizens Section */}
        <div className="bg-black/40 border border-[#C5A059]/30 rounded-xl p-6 backdrop-blur-sm relative z-10">
          <div className="absolute top-0 right-0 w-full h-[1px] bg-gradient-to-l from-transparent via-[#C5A059]/50 to-transparent rounded-t-xl" />
          <div className="flex items-center justify-between mb-6 pb-4 border-b border-[#2a2a2a]">
            <h3 className="text-sm font-mono text-[#C5A059] uppercase tracking-[0.2em] font-bold">
              CITIZENS (المواطنون)
            </h3>
            <span className="bg-[#111] text-[#C5A059] font-mono border border-[#C5A059]/30 rounded px-3 py-1 text-xs">
              {citizenRoles.length} OP(s)
            </span>
          </div>
          
          <div className="flex flex-wrap gap-3">
            {roles.map((r, i) => {
              const isMafia = [Role.GODFATHER, Role.SILENCER, Role.CHAMELEON, Role.MAFIA_REGULAR].includes(r);
              if (isMafia) return null;
              return (
                <div key={i} className="bg-[#0a0a0a] border border-[#2a2a2a] rounded-lg p-2 flex items-center gap-3 hover:border-[#C5A059]/50 transition-colors group flex-1 min-w-[200px] sm:flex-none">
                  <div className="w-12 h-12 shrink-0 rounded bg-[#111] border border-[#333] flex items-center justify-center text-2xl grayscale opacity-60 group-hover:opacity-100 transition-opacity">
                    {ROLE_ICONS[r]}
                  </div>
                  <div className="relative flex-1">
                    <div 
                      onClick={() => setOpenDropdown(openDropdown === i ? null : i)}
                      className="w-full bg-transparent text-[#999] font-mono text-xs md:text-sm px-3 py-2 cursor-pointer tracking-widest font-bold flex justify-between items-center"
                      dir="ltr"
                    >
                      <span className="text-white pr-2 whitespace-nowrap">{ROLE_NAMES[r]}</span>
                      <span className="text-[#C5A059] text-[10px] shrink-0">▼</span>
                    </div>

                    <AnimatePresence>
                      {openDropdown === i && (
                        <motion.div 
                          initial={{ opacity: 0, y: -10 }} 
                          animate={{ opacity: 1, y: 0 }} 
                          exit={{ opacity: 0, y: -10 }}
                          className="absolute top-full right-0 w-[220px] mt-2 bg-[#0c0c0c] border border-[#C5A059]/40 rounded-lg shadow-2xl z-50 overflow-hidden"
                          dir="rtl"
                        >
                          <div className="max-h-[220px] overflow-y-auto">
                            {allRolesList.map(role => (
                              <div 
                                key={role}
                                onClick={() => { handleRoleChange(i, role); setOpenDropdown(null); }}
                                className={`px-4 py-3 flex items-center gap-3 cursor-pointer hover:bg-[#C5A059]/20 transition-colors ${r === role ? 'bg-[#C5A059]/10 border-l-2 border-[#C5A059]' : ''}`}
                              >
                                <span className="text-xl grayscale opacity-70 w-6 text-center">{ROLE_ICONS[role]}</span>
                                <span className="font-mono text-xs text-[#C5A059] flex-1">{ROLE_NAMES[role]}</span>
                              </div>
                            ))}
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      <div className="text-center mt-12 mb-6">
        <button onClick={handleConfirm} className="btn-premium px-12 py-5 w-full md:w-auto min-w-[300px]">
          <span className="text-white text-xs tracking-[0.3em] font-bold">CONFIRM OP_DISTRIBUTION</span>
        </button>
      </div>

    </div>
  );
}
